# -*- coding: utf-8 -*-
"""GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jS82kMSxvBvFeBOwBosCTxANz2I2yjOu
"""

import requests
import torch
import torch.nn as nn
from torch.nn import functional as F

# The URL for the raw text data
data_url = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'

# Request the data
response = requests.get(data_url)

# Save the content to a local file
file_path = 'input.txt'
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(response.text)

print(f"Tiny Shakespeare dataset downloaded and saved to: {file_path}")

with open('input.txt', 'r', encoding='utf-8') as f:
  text = f.read()

vocabulary = list(set(text))

stoi = {ch:i for i, ch in enumerate(vocabulary)}
itos = {i:ch for i, ch in enumerate(vocabulary)}

encode = lambda s: [stoi[ch] for ch in s]
decode = lambda ii: ''.join([itos[i] for i in ii])

encoded_text = encode("Hello world!")
print(f"Encoded 'Hello world!': {encoded_text}")
print(f"Decoded back: {decode(encoded_text)}")

data = torch.tensor(encode(text), dtype=torch.long)

n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

